# Generated by Django 5.1.5 on 2025-01-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=512)),
                ('meaning', models.CharField(max_length=512)),
                ('example', models.CharField(blank=True, max_length=1024, null=True)),
                ('rate', models.SmallIntegerField(default=0)),
                ('last_reply', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('next_review_date', models.DateField()),
            ],
        ),
    ]
