# Generated by Django 5.1.5 on 2025-02-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='answer',
            field=models.BooleanField(default=False),
        ),
    ]
