# Generated by Django 5.1.5 on 2025-02-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_flashcard_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='answer',
        ),
    ]
